apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus-app
          image: your-registry/quarkus-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_PROFILE
              value: "prod"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
