apiVersion: v1
kind: Service
metadata:
  name: micronaut-service
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: micronaut-app
