apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ts-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-ts-app
  template:
    metadata:
      labels:
        app: react-ts-app
    spec:
      containers:
        - name: react-ts-app
          image: your-registry/react-ts-app:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
