apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: production
  labels:
    app: react-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: react-app
        tier: frontend
    spec:
      containers:
      - name: react-app
        image: your-registry/react-app:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          value: "production"
      imagePullSecrets:
      - name: registry-credentials
      restartPolicy: Always
