apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: production
  labels:
    app: react-app
    tier: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: react-app
    tier: frontend
  sessionAffinity: None
  externalTrafficPolicy: Cluster
