apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nextjs-app
