apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ts-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-ts-app
  template:
    metadata:
      labels:
        app: node-ts-app
    spec:
      containers:
        - name: node-ts-app
          image: your-registry/node-ts-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
