apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: production
  labels:
    app: fastapi-app
    tier: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: fastapi-app
    tier: backend
  sessionAffinity: None
